<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2015-12-09T21:59:16+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'AMAP Ploërmel',
    'version_installed' => '5.7.5.3',
    'misc' => array(
        'access_entity_updated' => 1449258643,
        'default_supermint_preset_id' => '5',
        'do_page_reindex_check' => false,
        'latest_version' => '5.7.5.3',
        'default_jpeg_image_compression' => '80',
    ),
    'editor' => array(
        'plugins' => array(
            'selected' => array(
                'themefontcolor',
                'themeclips',
                'concrete5lightbox',
                'undoredo',
                'specialcharacters',
                'table',
            ),
        ),
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ),
    'theme' => array(
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ),
    'marketplace' => array(
        'enabled' => '1',
        'intelligent_search_help' => '1',
    ),
    'external' => array(
        'news_overlay' => '0',
        'news' => '0',
    ),
    'white_label' => array(
        'logo' => false,
        'logo_fid' => '0',
        'name' => '',
    ),
);
