<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2015-09-14T18:30:14+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      version_installed
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Supermint',
    'version_installed' => '5.7.5.2',
    'misc' => array(
        'access_entity_updated' => 1441373781,
        'default_supermint_preset_id' => '4',
        'do_page_reindex_check' => false,
        'latest_version' => '5.7.5.1',
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ),
    'theme' => array(
        'compress_preprocessor_output' => false,
    ),
    'editor' => array(
        'concrete' => array(
            'enable_filemanager' => '1',
            'enable_sitemap' => '1',
        ),
        'plugins' => array(
            'selected' => array(
                'undoredo',
                'concrete5lightbox',
                'specialcharacters',
                'table',
                'themefontcolor',
                'themeclips',
            ),
        ),
    ),
);
