<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-03-08T15:56:11+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      version_db_installed
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'site' => 'Supermint',
    'version_installed' => '8.1.0',
    'version_db_installed' => '20170123000000',
    'misc' => [
        'access_entity_updated' => 1488984947,
        'default_supermint_preset_id' => '4',
        'do_page_reindex_check' => false,
        'latest_version' => '5.7.5.13',
        'login_redirect' => 'DESKTOP',
    ],
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
    ],
    'editor' => [
        'concrete' => [
            'enable_filemanager' => '1',
            'enable_sitemap' => '1',
        ],
        'plugins' => [
            'selected' => [
                'undoredo',
                'concrete5lightbox',
                'specialcharacters',
                'table',
                'themefontcolor',
                'themeclips',
            ],
        ],
    ],
];
