<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2015-12-03T11:05:27+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Anitya Flow',
    'version_installed' => '5.7.5.2',
    'misc' => array(
        'access_entity_updated' => 1448029246,
        'default_anitya_preset_id' => '3',
        'latest_version' => '5.7.5.3',
        'do_page_reindex_check' => false,
    ),
    'editor' => array(
        'plugins' => array(
            'selected' => array(
                'themefontcolor',
                'themeclips',
                'concrete5lightbox',
                'undoredo',
                'specialcharacters',
                'table',
            ),
        ),
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ),
    'theme' => array(
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ),
);
