<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-03-08T16:08:56+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.seo.tracking
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Anitya Flow',
            'concrete' => [
                'seo' => [
                    'tracking' => [
                        'code' => [
                            'header' => '',
                            'footer' => '',
                        ],
                    ],
                ],
            ],
            'seo' => [
                'tracking' => [
                    'code' => [
                        'header' => '',
                        'footer' => '',
                    ],
                ],
            ],
        ],
    ],
];
