<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2015-10-31T09:30:52+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Clara',
    'version_installed' => '5.7.5.2',
    'misc' => array(
        'access_entity_updated' => 1446129534,
        'default_anitya_preset_id' => 1,
        'do_page_reindex_check' => false,
        'latest_version' => '5.7.5.1',
    ),
    'editor' => array(
        'plugins' => array(
            'selected' => array(
                '0' => 'themefontcolor',
                '1' => 'themeclips',
                '4' => 'concrete5lightbox',
                '5' => 'undoredo',
                '6' => 'specialcharacters',
                '7' => 'table',
            ),
        ),
    ),
    'debug' => array(
        'detail' => 'debug',
        'display_errors' => true,
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ),
    'theme' => array(
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ),
);
