<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2015-12-15T12:03:13+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Supermint',
    'version_installed' => '5.7.5.3',
    'misc' => array(
        'access_entity_updated' => 1439299813,
        'default_supermint_preset_id' => '3',
        'do_page_reindex_check' => false,
        'latest_version' => '5.7.5.3',
    ),
    'debug' => array(
        'detail' => 'debug',
        'display_errors' => true,
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ),
    'theme' => array(
        'compress_preprocessor_output' => false,
    ),
);
