<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-03-08T16:48:39+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      version_db_installed
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.1.0',
    'version_db_installed' => '20170123000000',
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ],
    'misc' => [
        'seen_introduction' => true,
        'do_page_reindex_check' => false,
        'latest_version' => '5.7.5.13',
        'default_anitya_preset_id' => 1,
        'default_jpeg_image_compression' => '80',
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1488988074,
    ],
    'seo' => [
        'url_rewriting' => 1,
        'tracking' => [
            'code' => '<script>
  (function(i,s,o,g,r,a,m){i[\'GoogleAnalyticsObject\']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,\'script\',\'//www.google-analytics.com/analytics.js\',\'ga\');

  ga(\'create\', \'UA-17070622-7\', \'auto\');
  ga(\'send\', \'pageview\');

</script>',
            'code_position' => 'bottom',
        ],
    ],
    'debug' => [
        'detail' => 'debug',
        'display_errors' => true,
    ],
    'editor' => [
        'concrete' => [
            'enable_filemanager' => '1',
            'enable_sitemap' => '1',
        ],
        'plugins' => [
            'selected' => [
                'undoredo',
                'concrete5lightbox',
                'specialcharacters',
                'table',
                'themefontcolor',
                'themeclips',
            ],
        ],
    ],
    'marketplace' => [
        'enabled' => '1',
        'intelligent_search_help' => '0',
    ],
    'external' => [
        'news_overlay' => '0',
        'news' => '0',
    ],
    'white_label' => [
        'logo' => false,
        'logo_fid' => '0',
        'name' => '',
    ],
];
