<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-03-08T16:48:14+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.seo.tracking
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => null,
            'concrete' => [
                'seo' => [
                    'tracking' => [
                        'code' => [
                            'header' => '',
                            'footer' => '<script>
  (function(i,s,o,g,r,a,m){i[\'GoogleAnalyticsObject\']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,\'script\',\'//www.google-analytics.com/analytics.js\',\'ga\');

  ga(\'create\', \'UA-17070622-7\', \'auto\');
  ga(\'send\', \'pageview\');

</script>',
                        ],
                    ],
                ],
            ],
            'seo' => [
                'tracking' => [
                    'code' => [
                        'header' => '',
                        'footer' => '<script>
  (function(i,s,o,g,r,a,m){i[\'GoogleAnalyticsObject\']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,\'script\',\'//www.google-analytics.com/analytics.js\',\'ga\');

  ga(\'create\', \'UA-17070622-7\', \'auto\');
  ga(\'send\', \'pageview\');

</script>',
                    ],
                ],
            ],
        ],
    ],
];
