<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-03-08T15:53:28+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      version_db_installed
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.1.0',
    'version_db_installed' => '20170123000000',
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
    ],
    'misc' => [
        'seen_introduction' => true,
        'do_page_reindex_check' => false,
        'access_entity_updated' => 1488984757,
        'latest_version' => '5.7.5.13',
        'login_redirect' => 'DESKTOP',
    ],
    'debug' => [
        'detail' => 'debug',
        'display_errors' => true,
    ],
    'seo' => [
        'url_rewriting' => 1,
        'tracking' => [
            'code' => '<script>
  (function(i,s,o,g,r,a,m){i[\'GoogleAnalyticsObject\']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,\'script\',\'//www.google-analytics.com/analytics.js\',\'ga\');

  ga(\'create\', \'UA-17070622-8\', \'auto\');
  ga(\'send\', \'pageview\');

</script>',
            'code_position' => 'bottom',
        ],
    ],
];
