<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-03-08T15:44:49+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'site' => 'Supermint 3',
    'version_installed' => '8.1.0',
    'version_db_installed' => '20170123000000',
    'misc' => [
        'access_entity_updated' => 1488984212,
        'default_supermint_preset_id' => 1,
        'do_page_reindex_check' => false,
        'latest_version' => '8.1.0',
        'default_jpeg_image_compression' => '80',
        'modern_tile_thumbnail_fid' => '34',
        'modern_tile_thumbnail_bgcolor' => '',
        'favicon_fid' => '32',
        'iphone_home_screen_thumbnail_fid' => '33',
        'login_redirect' => 'DESKTOP',
    ],
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ],
    'editor' => [
        'concrete' => [
            'enable_filemanager' => '1',
            'enable_sitemap' => '1',
        ],
        'plugins' => [
            'selected' => [
                'undoredo',
                'specialcharacters',
                'table',
                'themefontcolor',
                'themeclips',
            ],
        ],
    ],
    'marketplace' => [
        'enabled' => '0',
        'intelligent_search_help' => '0',
    ],
    'external' => [
        'news_overlay' => '0',
        'news' => '0',
    ],
    'white_label' => [
        'logo' => false,
        'logo_fid' => '0',
        'name' => '',
    ],
    'debug' => [
        'detail' => 'debug',
        'display_errors' => true,
    ],
    'seo' => [
        'canonical_url' => '',
        'canonical_ssl_url' => '',
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => 0,
    ],
];
