<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2015-12-14T11:08:31+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Supermint 3',
    'version_installed' => '5.7.5.2',
    'misc' => array(
        'access_entity_updated' => 1432650984,
        'default_supermint_preset_id' => 1,
        'do_page_reindex_check' => false,
        'latest_version' => '5.7.4.2',
        'default_jpeg_image_compression' => '80',
        'modern_tile_thumbnail_fid' => '34',
        'modern_tile_thumbnail_bgcolor' => '',
        'favicon_fid' => '32',
        'iphone_home_screen_thumbnail_fid' => '33',
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ),
    'theme' => array(
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ),
    'editor' => array(
        'concrete' => array(
            'enable_filemanager' => '1',
            'enable_sitemap' => '1',
        ),
        'plugins' => array(
            'selected' => array(
                'undoredo',
                'specialcharacters',
                'table',
                'themefontcolor',
                'themeclips',
            ),
        ),
    ),
    'marketplace' => array(
        'enabled' => '0',
        'intelligent_search_help' => '0',
    ),
    'external' => array(
        'news_overlay' => '0',
        'news' => '0',
    ),
    'white_label' => array(
        'logo' => false,
        'logo_fid' => '0',
        'name' => '',
    ),
    'debug' => array(
        'detail' => 'debug',
        'display_errors' => true,
    ),
    'seo' => array(
        'canonical_url' => '',
        'canonical_ssl_url' => '',
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => 0,
    ),
);
