<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-03-08T15:43:38+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.seo.tracking
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Supermint 3',
            'misc' => [
                'favicon_fid' => '32',
                'iphone_home_screen_thumbnail_fid' => '33',
                'modern_tile_thumbnail_fid' => '34',
            ],
            'concrete' => [
                'seo' => [
                    'tracking' => [
                        'code' => [
                            'header' => '',
                            'footer' => '',
                        ],
                    ],
                ],
            ],
            'seo' => [
                'tracking' => [
                    'code' => [
                        'header' => '',
                        'footer' => '',
                    ],
                ],
            ],
        ],
    ],
];
