<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-03-08T16:16:14+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      version_db_installed
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'site' => 'Slate',
    'version_installed' => '8.1.0',
    'version_db_installed' => '20170123000000',
    'misc' => [
        'access_entity_updated' => 1488986124,
        'default_anitya_preset_id' => 1,
        'do_page_reindex_check' => false,
        'latest_version' => '5.7.5.6',
        'login_redirect' => 'DESKTOP',
    ],
    'editor' => [
        'plugins' => [
            'selected' => [
                '0' => 'themefontcolor',
                '1' => 'themeclips',
                '4' => 'concrete5lightbox',
                '5' => 'undoredo',
                '6' => 'specialcharacters',
                '7' => 'table',
            ],
        ],
    ],
    'debug' => [
        'detail' => 'debug',
        'display_errors' => true,
    ],
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ],
];
