<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2015-09-23T12:13:47+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Supermint',
    'version_installed' => '5.7.5.2',
    'misc' => array(
        'access_entity_updated' => 1439992051,
        'default_supermint_preset_id' => 1,
        'do_page_reindex_check' => false,
        'latest_version' => '5.7.5.1',
    ),
    'debug' => array(
        'detail' => 'debug',
        'display_errors' => true,
    ),
);
