<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-03-08T15:53:29+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      version_db_installed
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'site' => 'Supermint',
    'version_installed' => '8.1.0',
    'version_db_installed' => '20170123000000',
    'misc' => [
        'access_entity_updated' => 1488984759,
        'default_supermint_preset_id' => 1,
        'do_page_reindex_check' => false,
        'latest_version' => '5.7.5.13',
        'login_redirect' => 'DESKTOP',
    ],
    'debug' => [
        'detail' => 'debug',
        'display_errors' => true,
    ],
];
