<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2015-12-15T11:56:07+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      version_installed
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Supermint',
    'version_installed' => '5.7.5.3',
    'misc' => array(
        'access_entity_updated' => 1439992051,
        'default_supermint_preset_id' => 1,
        'do_page_reindex_check' => false,
        'latest_version' => '5.7.5.3',
    ),
    'debug' => array(
        'detail' => 'debug',
        'display_errors' => true,
    ),
);
